@QuizApp_HostAddress = http://localhost:5241

###
GET {{QuizApp_HostAddress}}/Questions
Accept: application/json

###
POST {{QuizApp_HostAddress}}/Questions
Content-Type: application/json
# {
#   "type": "multiple",
#       "difficulty": "medium",
#       "category": "Entertainment: Video Games",
#       "question": "What is not a default game mode in Counter-Strike (2000)?",
#       "correct_answer": "Arms Race",
#       "incorrect_answers": [
#         "Hostage Rescue",
#         "Bomb Defusal",
#         "Assassination"
#       ]
# }

###
# POST {{QuizApp_HostAddress}}/Questions/import
# Content-Type: application/json


###
POST {{QuizApp_HostAddress}}/Player
Content-Type: application/json
# {
#   "userName": "TestUser"
# }

###
GET {{QuizApp_HostAddress}}/Player
Content-Type: application/json


###
GET {{QuizApp_HostAddress}}/play/questions
content-type: application/json
###
POST {{QuizApp_HostAddress}}/play
content-Type: application/json
{
  "PlayerId":3,
  "QuestionId":7,
  "Answer": "Hanoi",
  "TimeTakenSeconds": 12
}
